---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  DATABASE_USERNAME: YWRtaW4=
  DATABASE_PASSWORD: cGFzc3dvcmQ=
  DATABASE_NAME: ZGI=
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.service.db.host .Values.service.db.sport .Values.service.db.dbname  | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: YWRtaW4=
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
  SERVER_PORT: "{{ .Values.config.port }}"
  SPRING_JPA_DATABASE: "{{ .Values.config.database }}"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "{{ .Values.config.ddl }}"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "{{ .Values.config.driver }}"
  PROFILES_URI: http://auth.auth:9000/
  JWT_SECRET: "{{ .Values.deployment.app.jwtsecret }}"